apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080 # where microservice is running
    protocol: TCP
    targetPort: 8080 # Internal communication within cluster
    nodePort: 30123 #External Traffic
  

